version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=your_mongodb_connection_string
      - JWT_SECRET=your_jwt_secret
    # Uncomment the following if you want to use a local MongoDB container
    # depends_on:
    #   - mongo
  # mongo:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
# volumes:
#   mongo_data:
